Eval:
  Exclude:
    - "Rakefile"

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Exclude:
    - "bin/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/Encoding:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false
